name = "MDTrajectoryFiles"
uuid = "e55597f1-1f81-4e61-9c07-9db33debcbd4"
authors = ["Uliano Guerrini <uliano.guerrini@gmail.com> and contributors"]
version = "0.1.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
